### ISSUE TITLE
Data Augmentation

### ISSUE THREAD

**Issue by CaptainAlready** [rsarka34/RDLINet#1]
Very nice structured paper and code as well, congrats! I have a question: It appears that you perform the data augmentation before splitting into train, test and validation sets. Wouldn't that lead to data leakage into the test and validation sets? Thanks!

**Comment by rsarka34** [comment]
Thanks for the comment. I agree with your concern about augmenting the validation and test data. However, I want to clarify that we have done the augmentation on the training set only...not on the other two sets. In this code, I have just given the basic flow of the deep learning model and training testing part. However, all the augmentation and other parts are not provided in the code

**Comment by CaptainAlready** [comment]
Perfect! Great job!

**Comment by rsarka34** [comment]
Thank you
